# Generated by Django 3.0.4 on 2020-03-22 23:54

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('img', models.CharField(max_length=2000)),
                ('price', models.CharField(max_length=50)),
                ('information', models.CharField(max_length=500)),
                ('facilities', models.CharField(max_length=500)),
                ('rent_includes', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('address_link', models.CharField(max_length=500)),
                ('score', models.IntegerField()),
                ('comments', models.TextField(max_length=2000)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'apartment',
            },
        ),
        migrations.CreateModel(
            name='evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_id', models.IntegerField()),
                ('user_id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('environment', models.IntegerField()),
                ('staff_service', models.IntegerField()),
                ('security', models.IntegerField()),
                ('cost_performance', models.IntegerField()),
                ('comment', models.CharField(max_length=2000)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'evaluation',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('favorite', models.CharField(default='[]', max_length=200)),
            ],
        ),
    ]
